### ISSUE TITLE
有个建议 建议弄个docker 部署或者docker-compose 部署 

### ISSUE THREAD

**Issue by laike** [anlityli/chatait-free#1]
目前的部署方案还是太复杂了 
看看后期能不能加入docker 和 docker compose 部署
谢谢

**Comment by anlityli** [comment]
> 目前的部署方案还是太复杂了 看看后期能不能加入docker 和 docker compose 部署 谢谢

有时间的时候，搞一个docker，谢谢建议

**Comment by anlityli** [comment]
docker部署方案已经发布，请参考部署说明
