### ISSUE TITLE
添加api key报这个提示，麻烦帮忙看下

### ISSUE THREAD

**Issue by codingstu** [anlityli/chatait-free#11]
{
    "error": 400,
    "message": "Error 1364: Field 'api_url' doesn't have a default value, INSERT INTO `c_config_openai`(`title`,`api_key`,`proxy`,`max_tokens`,`status`,`id`,`created_at`) VALUES('chatai','sk-------------','openai.com',500,1,1733924798293082112,1700903887) \n"
}

**Comment by anlityli** [comment]
用的master分支的代码编译的？如果是的话，记得把数据库c_config_openai表按照db目录的数据库文件增加一个api_url字段。
另外请编辑一下你的提问，你的提问暴露了你的openai的key

**Comment by codingstu** [comment]
好的，谢谢提醒
