### ISSUE TITLE
Post "https://api.openai.com/v1/chat/completions"

### ISSUE THREAD

**Issue by duwwtop** [anlityli/chatait-free#12]
![微信截图_20231215202236](https://github.com/anlityli/chatait-free/assets/83152852/65d4a859-ccab-43d4-94de-c3565aba2a32)
1.1.1不支持第三方api吗

**Comment by duwwtop** [comment]
能否发一下最新的docker 1.1.2支持第三方api的版本？

**Comment by anlityli** [comment]
> 能否发一下最新的docker 1.1.2支持第三方api的版本？

好的
