### ISSUE TITLE
1.13EOF

### ISSUE THREAD

**Issue by duwwtop** [anlityli/chatait-free#13]
![微信截图_20231218195622](https://github.com/anlityli/chatait-free/assets/83152852/0c9ed457-6b1d-49aa-9185-161da28bc15f)
![微信截图_20231218195657](https://github.com/anlityli/chatait-free/assets/83152852/bb921eb6-3bdd-4a38-adea-4e8b50eea1ca)
使用第三方api反代opnai会显示eof
使用中转api也是eof

**Comment by anlityli** [comment]
![image](https://github.com/anlityli/chatait-free/assets/11658297/d48d64d4-ea1e-4198-a5a3-714a7bb0b236)
把第三方接口的地址写完全，第三方接口的地址是 ```https://第三方接口域名/v1/chat/completions```

**Comment by duwwtop** [comment]
> ![图像](https://private-user-images.githubusercontent.com/11658297/291463974-d48d64d4-ea1e-4198-a5a3-714a7bb0b236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzQ4NjgsIm5iZiI6MTcwMjk3NDU2OCwicGF0aCI6Ii8xMTY1ODI5Ny8yOTE0NjM5NzQtZDQ4ZDY0ZDQtZWExZS00MTk4LWE1YTMtNzE0YTdiYjBiMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA4MjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlY2Y5MjUzOWRkNDU0OWNhOTQ4ODUyZmRiMDg0ZTEyY2E1Zjk5MzAwOWIyZGY4MDM0M2M2OGRlN2Q4NTUzODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrxZhSOhZ6AlyP_i0-CZyGZohAV_HHgoAlecoGRxTf4)把第三方接口的地址写完全，第三方接口的地址是`https://第三方接口域名/v1/chat/completions`

那如果使用第三方中转API呢  现在是否支持？

**Comment by anlityli** [comment]
有第三方中转的文档吗？我看看。

**Comment by anlityli** [comment]
经测试第三方中转也没有问题，只要接口地址写完全，不能只写域名就能成功。
