### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by chostlww** [anlityli/chatait-free#14]
docker部署报错：Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
可能因为nginx配置问题

**Comment by anlityli** [comment]
我又用docker部署了一次，没发现问题。你的nginx配置是再宿主机上按照我提供的nginx配置文件配置的吗？另外,docker部署的话，域名是www.xxx.com，A记录是www。后台的域名是backend.xxx.com，A记录是backend。前台服务端接口的域名是chat-frontend-api.xxx.com， A记录是chat-frontend-api， 后台服务端接口的域名是 chat-backend-api.xxx.com，A记录是chat-backend-api，这些都是固定的不能改。因为这些都是打包好的，否则前台前端调不到接口。

**Comment by chostlww** [comment]
![Screenshot_20231219_111641.jpg](https://github.com/anlityli/chatait-free/assets/79144354/09faa34d-136c-4c40-88c0-2424289cc32a)

域名解析和a记录应该没问题是按教程来走的，可能是我部署nginx文件那一步没弄好

**Comment by anlityli** [comment]
宿主机nginx配置发一下看看

**Comment by chostlww** [comment]
![image](https://github.com/anlityli/chatait-free/assets/79144354/1431f984-69b8-4f67-9af1-9219ad51d186)
现在报错这个

**Comment by chostlww** [comment]
已经部署好了，谢谢大佬

**Comment by anlityli** [comment]
OK
