### ISSUE TITLE
inject() can only be used inside setup() or functional components.

### ISSUE THREAD

**Issue by bobwong89757** [anlityli/chatait-free#16]
<img width="1146" alt="image" src="https://github.com/anlityli/chatait-free/assets/6356061/c58fe5e6-dca3-4a2c-b5aa-0d09ea5abb28">

vue版本3.4.15

**Comment by bobwong89757** [comment]
需要修改一下
export const getActive = (maxLevel = 3): string => {
  const route = useRoute()
  if (isNil(route)){
    return ''
  }
  ...
}

**Comment by anlityli** [comment]
感谢纠正
