### ISSUE TITLE
chatait-backend-vue build 失败？

### ISSUE THREAD

**Issue by zurmokeeper** [anlityli/chatait-free#18]
chatait-backend-vue build 在window 和linux 上都build 失败, npm run build

> chatgpt-backend@1.2.0 build D:\code\git\chatait-free\chatait-backend-vue
> vue-tsc --noEmit && vite build --mode release

src/layouts/components/MenuContent.vue:59:45 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

59   if (typeof item.icon === "string") return <t-icon name={item.icon} />;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/layouts/components/MenuContent.vue:59

请问有build 好 chatait-backend-vue 和 chatait-frontend-vue的 dist 文件吗？

直接拉的最新代码

**Comment by anlityli** [comment]
用 npm run buildWhitoutLint
