### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by 51sky** [anlityli/chatait-free#5]
提示：Network Error

这是啥问题

**Comment by anlityli** [comment]
network error一般是域名解析的有问题
另外，数据库导入失败用 https://github.com/anlityli/chatait-free/blob/main/db/chatait_db.sql 文件

**Comment by anlityli** [comment]
如果域名解析没有问题，打开浏览器的开发者工具，把控制台的报错截图或者复制报错内容。

**Comment by 51sky** [comment]
数据库好了

![1](https://github.com/anlityli/chatait-free/assets/49282186/7f95f8fa-76a3-4ad3-a09f-d1e8d621c7ef)

**Comment by anlityli** [comment]
这是宿主机的nginx没配置正确，出现了跨域问题。
宿主机的nginx按照这个文件配置https://github.com/anlityli/chatait-free/blob/main/nginx/chatait.conf

**Comment by 51sky** [comment]
> 这是第一步机器的nginx没有配置正确，出现了跨域问题。 第一步机器的nginx按照这个文件配置，换成你的域名。[https://github.com/anlityli/chatait-free/blob/main/nginx /chatait.conf](https://github.com/anlityli/chatait-free/blob/main/nginx/chatait.conf)

已经重新设置，域名也重新做了解析，问题依然纯在。

另外，配置文件中这个目录是不是有误？
![456](https://github.com/anlityli/chatait-free/assets/49282186/beac36f4-ccdc-4966-9f66-6d680b324ea4)

**Comment by anlityli** [comment]
对不起，我的错误，docker部署的话，宿主机的nginx应该用这个文件 https://github.com/anlityli/chatait-free/blob/main/docker/chatait.conf
