### ISSUE TITLE
前端部署问题

### ISSUE THREAD

**Issue by chostlww** [anlityli/chatait-free#7]
![Image_1700066937568.jpg](https://github.com/anlityli/chatait-free/assets/79144354/30e6545d-53f0-4303-94ee-4c8ffb16d15f)

**Comment by chostlww** [comment]
网页访问不上，nginx已经配置好域名了

**Comment by anlityli** [comment]
常规部署还是docker部署，如果是常规部署需要把服务端放到systemctl里面启动，或者后台启动，否则直接在终端启动的话，打断命令服务就断了。
