### ISSUE TITLE
代理地址

### ISSUE THREAD

**Issue by goldkiss** [anlityli/chatait-free#8]
代理地址怎么设置？支持些什么？可以用第三方api吗？

**Comment by anlityli** [comment]
支持http代理，可以是从服务器上安装各种代理客户端连接你的代理服务器，然后，chatait网站设置客户端提供的http代理。例如：http://127.0.0.1:1087

**Comment by goldkiss** [comment]
还有那个plus等级有啥用？没地方设置啊，还有充值只有现金，没有次数，后台也不能修改次数

**Comment by anlityli** [comment]
会员等级：
系统设置--级别列表 可以设置这个级别的会员每个月赠送的提问次数，到期清除没用完的次数，充入新的次数。

充值次数：
财务管理--钱包列表 可以给每个会员增加或减少对应钱包的次数。钱包类型可以选择不同的提问类型次数。如果只有现金没有其他的钱包，安装最新的1.1.1版本

**Comment by goldkiss** [comment]
感谢，希望可以支持三方API，那就代理都不用了，网站很好用，start+1。

**Comment by goldkiss** [comment]
midjourney设置还不太会，能否也写一下说明感谢

**Comment by anlityli** [comment]
> midjourney设置还不太会，能否也写一下说明感谢

midjourney 暂时可以参考这个地址设置：https://github.com/novicezk/midjourney-proxy/blob/main/docs/discord-params.md
另外 MidjourneyBotID 设置 936929561302675456 ,应该是固定的。另外有其他人反应 HuggingFaceToken 也需要设置否则不出图，如果有HuggingFace账号就设置这个账号的token如果没有就随便填一个，这个token的作用是当发生错误时，可以跳人机校验。

**Comment by anlityli** [comment]
> 感谢，希望可以支持三方API，那就代理都不用了，网站很好用，start+1。

第三方API，以后有空的时候，可以加一个，如果你会编译go的话，可以直接修改代码中对应请求openai地址的常量就行。

**Comment by goldkiss** [comment]
MidjourneyBotID
BotToken
会话ID
这几个参数哪里找？找不到，哈哈

**Comment by anlityli** [comment]
打开浏览器的调试工具，在原版的midjourney中发一个生成图片的任务，会看到一个请求，在请求里面查看请求的内容，中application_id就是MidjourneyBotID，session_id就是会话ID，至于BotToken如果用UserWss模式则不用填

**Comment by goldkiss** [comment]
感谢支持666

**Comment by chostlww** [comment]
> > 感谢，希望可以支持三方API，那就代理都不用了，网站很好用，start+1。
> 
> 第三方API，以后有空的时候，可以加一个，如果你会编译go的话，可以直接修改代码中对应请求openai地址的常量就行。

请问相关代码在哪个路径呢

**Comment by anlityli** [comment]
https://github.com/anlityli/chatait-free/blob/main/chatait-public-lib/library/api/openai/constant.go
